// Auto-generated by deploy.sh
// DO NOT EDIT MANUALLY

import abi from './abi.json';

export const contractConfig = {
  address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0" as const,
  abi: abi,
  network: {
    name: "anvil" as const,
    chainId: 31337 as const,
  },
} as const;

// Contract artifacts location
export const CONTRACT_ABI_PATH = "./SupplyChainTracker.json";

// Export contract address for convenience
export const CONTRACT_ADDRESS = "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0" as const;

// Export ABI separately for convenience
export { abi };
