// Auto-generated by deploy.sh
// DO NOT EDIT MANUALLY

import abi from './abi.json';

export const contractConfig = {
  address: "0x5fbdb2315678afecb367f032d93f642f64180aa3" as const,
  abi: abi,
  network: {
    name: "anvil" as const,
    chainId: 31337 as const,
  },
} as const;

// Contract artifacts location
export const CONTRACT_ABI_PATH = "./SupplyChainTracker.json";

// Export contract address for convenience
export const CONTRACT_ADDRESS = "0x5fbdb2315678afecb367f032d93f642f64180aa3" as const;

// Export ABI separately for convenience
export { abi };
